version: '3.8'
services:
  php-mysql-environment:
    container_name: cli
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    links:
      - mysql-db
    volumes:
      - '.:/var/www/html/'
    ports:
      - '8888:80'
    networks:
      - my_project_network
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - '9906:3306'
    networks:
      - my_project_network

networks:
  my_project_network: